version: "3.8"
services:
    db:
        image: postgres:16.1-alpine
        restart: always
        environment:
            - POSTGRES_HOST=${PG_HOST}
            - POSTGRES_PORT=${PG_PORT}
            - POSTGRES_DB=${PG_DATABASE}
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
        ports:
            - "${PG_PORT}:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data:rw

volumes:
    postgres-data: